CREATE TABLE IF NOT EXISTS ScanIds (
scan_id INTEGER PRIMARY KEY AUTOINCREMENT,
sid FLOAT(8) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MotorMnes (
motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
scan_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES ScanIds(scan_id)*/,
motor_mne VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MotorPositions (
motor_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES MotorMnes(motor_id)*/,
motor_position FLOAT
);
