CREATE TABLE IF NOT EXISTS DID (
dataset_id INTEGER PRIMARY KEY AUTOINCREMENT,
did VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MotorMnes (
motor_id INTEGER PRIMARY KEY AUTOINCREMENT,
dataset_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES DID(dataset_id)*/,
motor_mne VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MotorPositions (
motor_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES MotorMnes(motor_id)*/,
motor_position FLOAT
);
