CREATE TABLE IF NOT EXISTS ScanIds (
scan_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
sid BIGINT UNSIGNED NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MotorMnes (
motor_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
scan_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES ScanIds(scan_id)*/,
motor_mne VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MotorPositions (
motor_id INTEGER NOT NULL /*FOREIGN KEY REFERENCES MotorMnes(motor_id)*/,
motor_position DOUBLE
);
